### ISSUE TITLE
docs: agree on a proper name

### ISSUE THREAD

**Issue by AngryMaciek** [AngryMaciek/warlock#28]
We need to come up with a better name; `demon-runner` is just a placeholder (which I personally started to dislike heavily) as this is a _runner_ (type of software) for the _demon_ tool.

@robjohnnoble @vesmanojlovic @blair_colyer  
Please write your suggestions in this issue. Most importantly, the name should be catchy. May or may not be descriptive, may or may not be an acronym depending on the choice. The more links we find between the name and "demon", "workflow", "pop.gen" etc. the better.

Also, and that is actually very important, there should not already exist another software with the same name in the same area (pop.gen/math.modeling).

**Comment by AngryMaciek** [comment]
This software is a big machinery above the demon (or demons, as it actually **spawns** multiple demons (jobs) running around on the cluster!) Therefore I was thinking of sth in this hellish direction. Sth that spawns demons... But on the other hand we cannot go into full occultistic territory, that would not suit research software. So maybe not necessarily **devil** but how about **wizard** or **sorcerer**?

**Comment by vesmanojlovic** [comment]
_**N.B. All of the below draws mostly from Tolkien's and Tolkien-adjacent fantasy works - statements may not hold across cultures.**_

I like the mage direction, but would suggest **warlock** or **shaman**, as a stereotypical wizard is a magic user who has learned the ways of the arcane through academic means, and a sorcerer is a naturally gifted magic user, neither necessarily associated with demons.

A warlock, on the other hand, gains their powers from a pact they have formed with a powerful otherworldly entity (such as a demon). A shaman, depending on where you look up the term of course, could be interpreted as a wielder of magical powers they harness from summoning and controlling spirits of more powerful creatures (including demons). 
The last one that comes to mind is **summoner**, though not sure I want to take Riot Games on for a legal battle over the term.

Alternatively, I know you said going full occult is probably not appropriate, but I think Lilith deserves her hat thrown in the ring as well. A bit less occult, and a bit more nerdy are Tolkien's works - Melkor/Morgoth being the first Dark Lord and source of evil in Arda.

**Comment by robjohnnoble** [comment]
I like this direction. Other related terms include evoker and conjuror (https://en.wikipedia.org/wiki/Evocation). I agree we don't want to go too occult or risk offending anyone.

**Comment by robjohnnoble** [comment]
Comments on related names suggested so far:

1. wizard - Not distinctive enough? Cheesy?
2. shaman - Could offend people (https://en.wikipedia.org/wiki/Shamanism#Criticism_of_the_term)
3. Lilith - Actually a demon rather than a summoner of demons
4. Melkor/Morgoth - Too nerdy?
5. evoker / summoner - Too strange?
6. conjuror - Makes me think of children's parties
7. warlock - Good, though not specifically linked to demons
8. sorcerer - Also good. More positive connotations

**Comment by AngryMaciek** [comment]
> Comments on related names suggested so far:
> 
> 1. wizard - Not distinctive enough? Cheesy?
> 2. shaman - Could offend people (https://en.wikipedia.org/wiki/Shamanism#Criticism_of_the_term)
> 3. Lilith - Actually a demon rather than a summoner of demons
> 4. Melkor/Morgoth - Too nerdy?
> 5. evoker / summoner - Too strange?
> 6. conjuror - Makes me think of children's parties
> 7. warlock - Good, though not specifically linked to demons
> 8. sorcerer - Also good. More positive connotations

1. Definitely, out
2. I liked it but I understand, out
3. We could easily jump on the hype for the [upcoming Blizzard game](https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc3/Diablo_4_header.jpg) with this one, but I guess an actual demon from the Judaic mythology may be just a little too much... (or is it?)
4. Nothing else is related to Tolkien here, feels out of place...
5. I like _evoker_ a lot; summoner doesn't sound that catchy IMO
6. Well, you have kids so I take your word on this one :)
7. I agree.
8. Following @vesmanojlovic : sorcerer is a different kind of magic user... I'd prefer sth with a clear link to summoning/spawning demons, that's all we need.

**Comment by robjohnnoble** [comment]
Great. So top choices so far are

- evoker
- warlock

This counts against evoker: https://github.com/wtsi-medical-genomics/evoker
