### ISSUE TITLE
`docker.service` fails to start

### ISSUE THREAD

**Issue by vesmanojlovic** [AngryMaciek/warlock#47]
### Initial check.

- [X] I added a very descriptive title above.
- [X] I searched through the issues in this repository to find a similar problem, but didn't find any.
- [X] I searched through Google (including the 2nd page of results) and didn't find any relevant information.
- [ ] I asked ChatGPT for help but did not get any meaningful response.

### Please describe what triggered the error.

Installing `docker` and attempting to start it on Arch Linux via `systemd`. 

### What did you expect to happen?

Expected a local Docker engine to start running. 

### What went wrong?

```
× docker.service - Docker Application Container Engine
     Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; preset: disabled)
     Active: failed (Result: exit-code) since Tue 2023-05-30 18:14:53 BST; 3min 21s ago
TriggeredBy: × docker.socket
       Docs: https://docs.docker.com
    Process: 55042 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 55042 (code=exited, status=1/FAILURE)
        CPU: 111ms

May 30 18:14:53 vesheljinn systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
May 30 18:14:53 vesheljinn systemd[1]: Stopped Docker Application Container Engine.
May 30 18:14:53 vesheljinn systemd[1]: docker.service: Start request repeated too quickly.
May 30 18:14:53 vesheljinn systemd[1]: docker.service: Failed with result 'exit-code'.
May 30 18:14:53 vesheljinn systemd[1]: Failed to start Docker Application Container Engine.

```
### Please specify your 𝘤𝘰𝘯𝘥𝘢 version.

23.3.1

### Operating System

Linux

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/AngryMaciek/warlock/blob/master/CODE_OF_CONDUCT.md)

**Comment by AngryMaciek** [comment]
I need some more specifics:

- What was your exact command that is failing?
- How did you install _Docker_?
- What has `systemd` to do with this?
- Are other containers built for u normally?
- Have u ever seen this error before?

**Comment by vesmanojlovic** [comment]
> * What was your exact command that is failing?

`systemctl start docker.service` is the main one, as running any `docker` command returns an error saying the service is not running.
> * How did you install _Docker_?

`pacman -S docker`
> * What has `systemd` to do with this?

It's the default system configuration software for Arch.
> * Are other containers built for u normally?

No, this is my first time trying docker. Clean install of `docker` following the official documentation. 
> * Have u ever seen this error before?

Not outside this use case, but starting docker is the main issue so I suspect other containers would result in the same error.

**Comment by AngryMaciek** [comment]
>  service is not running.

Well, yes, first you need to start the engine to be able to run any _docker_ commands

Hmm, I've never worked on Arch, cannot say if the installation was correct or not...

>  starting docker is the main issue so I suspect other containers would result in the same error.

I think this is pretty critical, could you please check another container?  
Could you please try my [old data-analytic container](https://github.com/AngryMaciek/SC4DA#creating-and-running-a-docker-container) and let me know how it went? Alternatively (if sth fails there), any other from DockerHub, ex: default _miniconda3_ would do.

I have just tried _warlock_ myself on another machine with Docker on Ubuntu 22.04 and worked fine.

**Comment by vesmanojlovic** [comment]
So yeah, the problem is likely somewhere on my Arch laptop, and I haven't yet figured out what's up.
Ran it fine yesterday in a virtual machine on my girlfriend's Windows laptop, and also on my office computer running Ubuntu today.

**Comment by AngryMaciek** [comment]
Alright, thats what I suspected, given the container builds and runs on the CI: https://github.com/AngryMaciek/warlock/actions/runs/4942368731/jobs/8835817398

I consider it closed then!
